name: Publish Release

on:
  workflow_dispatch:
  
env:
  PROJECT_PATH: Common/Common.csproj
  
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
       fetch-depth: 0
        
    - name: Get Common Version
      uses: kzrnm/get-net-sdk-project-versions-action@v1.3.0
      id: get-version
      with:
        proj-path: ${{ env.PROJECT_PATH }}
        
    - name: Create Github Release
      uses: actions/create-release@v1.1.4
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VersionName: v${{steps.get-version.outputs.version-prefix}}
      with:
        tag_name: ${{ env.VersionName }}
        release_name: ${{ env.VersionName }}
         
  changelog:
    needs: build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Get Common Version
      uses: kzrnm/get-net-sdk-project-versions-action@v1.3.0
      id: get-version
      with:
        proj-path: ${{ env.PROJECT_PATH }}
    
    - name: Install auto-changelog Package   
      run: npm install -g auto-changelog  
    
    - name: Generate CHANGELOG.md
      run: auto-changelog --commit-limit false --starting-version v${{steps.get-version.outputs.version-prefix}} --ending-version v${{steps.get-version.outputs.version-prefix}} --hide-credit
         
    - name: Get Latest Github Release
      id: latest_release
      uses: kaliber5/action-get-release@v1
      with:
        token: ${{ github.token }}
        latest: true 
        
    - name: Read CHANGELOG.md Content
      id: changelog
      uses: jaywcjlove/github-action-read-file@main
      with:
        localfile: CHANGELOG.md
    
    - name: Update Github Release with CHANGELOG.md
      uses: kaliber5/action-update-release@v1
      with:
        token: ${{ github.token }}
        id: ${{ steps.latest_release.outputs.id }}
        body: ${{ steps.changelog.outputs.content }}
